site_name: NICA e.V. Documentation
site_url: https://nica-ev.github.io/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - navigation.path
    - navigation.prune
    - toc.follow

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - callouts
  - tags:
      tags_file: tags.md

nav:
  - Home: index.md
  - Themen:
    - Digitale Infrastruktur: digital-infrastruktur.md
    - Wordpress: wordpress.md
    - Buchhaltung: buchhaltung.md
    - Nextcloud: nextcloud.md
  - Mitmachen: github-for-users.md
