site_name: My Docs
theme:
  name: windmill
nav:
  - Home: index.md
  - Wordpress:
    - Neue Seite erstellen: wordpress-pages.md
  - Stuff:
    - Dokumentations System: doc-sys.md
    - Github: github-for-users.md
