from __future__ import annotations

import posixpath
from pathlib import Path, PurePosixPath
from typing import Any
from urllib.parse import quote

from base_labels import extract_display_names, labels_for_language, unquote_yaml_scalar

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
TECHNICAL_IDENTITY_COLUMNS = {"path", "file", "file.path"}


def render_dynamic(data: Any, page_path: Path, config: dict[str, str]) -> tuple[str, list[str]]:
    rows = extract_rows(data)
    warnings: list[str] = []
    language = language_mode_value(page_path, config)
    if language:
        before = len(rows)
        rows = [row for row in rows if row_language(row) in ("", language)]
        if before != len(rows):
            warnings.append(f"language filter kept {len(rows)}/{before} rows for {language}")

    output_format = (config.get("format") or "table").strip().lower()
    if output_format == "list":
        return render_list_rows(rows, page_path), warnings
    if output_format not in {"", "table"}:
        warnings.append(f"unsupported format {output_format}; rendered table")
    return render_table_rows(rows, page_path, config), warnings


def render_table(data: Any, page_path: Path, config: dict[str, str]) -> tuple[str, list[str]]:
    return render_dynamic(data, page_path, {**config, "format": "table"})


def render_table_rows(rows: list[dict[str, Any]], page_path: Path, config: dict[str, str]) -> str:

    columns = base_view_columns(config, page_path, rows) or infer_columns(rows)

    if not columns:
        return "<!-- dynamic: no rows returned -->"

    table_rows = [
        [render_cell(row_value(row, column), column, row, page_path) for column in columns]
        for row in rows
    ]
    widths = table_widths([columns, *table_rows])
    lines = [
        generated_comment("table"),
        "",
        padded_table_row(columns, widths),
        padded_table_row(["-" * max(3, width) for width in widths], widths),
    ]
    for row in table_rows:
        lines.append(padded_table_row(row, widths))
    return "\n".join(lines)


def render_list_rows(rows: list[dict[str, Any]], page_path: Path) -> str:
    if not rows:
        return "<!-- dynamic: no rows returned -->"
    lines = [generated_comment("list"), ""]
    for row in rows:
        lines.append(f"- {render_row_link(row, page_path)}")
    return "\n".join(lines)


def generated_comment(output_format: str) -> str:
    return f"<!-- Generated by tools/dynamic_pages.py; edit the dynamic block config, not this {output_format}. -->"


def extract_rows(data: Any) -> list[dict[str, Any]]:
    if isinstance(data, list):
        return [normalize_row(item) for item in data if isinstance(item, dict)]
    if isinstance(data, dict):
        for key in ("rows", "items", "results", "data", "files"):
            value = data.get(key)
            if isinstance(value, list):
                return [normalize_row(item) for item in value if isinstance(item, dict)]
        if all(not isinstance(value, (list, dict)) for value in data.values()):
            return [normalize_row(data)]
    return []


def normalize_row(row: dict[str, Any]) -> dict[str, Any]:
    normalized: dict[str, Any] = {}
    for key, value in row.items():
        normalized[str(key)] = value
    if "file" not in normalized:
        for key in ("path", "file.path", "basename", "name"):
            if key in normalized:
                normalized["file"] = normalized[key]
                break
    return normalized


def infer_columns(rows: list[dict[str, Any]]) -> list[str]:
    columns: list[str] = []
    for row in rows:
        for key in row:
            if key not in columns:
                columns.append(key)
    columns = [column for column in columns if column.lower() not in TECHNICAL_IDENTITY_COLUMNS]
    return columns


def base_view_columns(config: dict[str, str], page_path: Path, rows: list[dict[str, Any]]) -> list[str]:
    base = config.get("base", "").strip()
    view = config.get("view", "").strip()
    if not base or not view or not rows:
        return []
    base_path = (ROOT / base).resolve()
    try:
        base_path.relative_to(ROOT.resolve())
    except ValueError:
        return []
    if not base_path.is_file():
        return []

    order = base_view_order(base_path, view)
    if not order:
        return []

    language = page_language(page_path)
    try:
        localized_labels = labels_for_language(base_path, language) if language else {}
    except Exception:
        localized_labels = {}
    try:
        source_labels = extract_display_names(base_path.read_text(encoding="utf-8"))
    except OSError:
        source_labels = {}

    columns: list[str] = []
    for property_name in order:
        column = resolve_base_property_column(property_name, rows, localized_labels, source_labels)
        if column and column not in columns:
            columns.append(column)
    return columns


def base_view_order(base_path: Path, view_name: str) -> list[str]:
    try:
        lines = base_path.read_text(encoding="utf-8-sig").splitlines()
    except OSError:
        return []
    for block in view_blocks(lines):
        if view_block_name(block) == view_name:
            return view_block_order(block)
    return []


def view_blocks(lines: list[str]) -> list[list[str]]:
    blocks: list[list[str]] = []
    in_views = False
    current: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped == "views:":
            in_views = True
            continue
        if not in_views:
            continue
        if stripped and not line.startswith((" ", "\t")):
            break
        if line.startswith("  - "):
            if current:
                blocks.append(current)
            current = [line]
            continue
        if current:
            current.append(line)
    if current:
        blocks.append(current)
    return blocks


def view_block_name(block: list[str]) -> str:
    for line in block:
        stripped = line.strip()
        if stripped.startswith("name:"):
            return unquote_yaml_scalar(stripped.split(":", 1)[1])
    return ""


def view_block_order(block: list[str]) -> list[str]:
    order: list[str] = []
    order_indent: int | None = None
    for line in block:
        stripped = line.strip()
        indent = len(line) - len(line.lstrip(" "))
        if order_indent is None:
            if stripped == "order:":
                order_indent = indent
            continue
        if not stripped:
            continue
        if indent <= order_indent:
            break
        if stripped.startswith("- "):
            order.append(unquote_yaml_scalar(stripped[2:]))
    return order


def resolve_base_property_column(
    property_name: str,
    rows: list[dict[str, Any]],
    localized_labels: dict[str, str],
    source_labels: dict[str, str],
) -> str:
    property_key = base_property_key(property_name)
    candidates = [
        property_name,
        property_key,
        property_name.removeprefix("formula."),
        property_name.removeprefix("file."),
        localized_labels.get(property_key, ""),
        source_labels.get(property_key, ""),
    ]
    if property_name == "file.name":
        candidates.extend(["file", "path", "name", "basename"])
    for candidate in candidates:
        column = resolve_row_column(candidate, rows)
        if column:
            return column
    return ""


def base_property_key(property_name: str) -> str:
    if property_name.startswith(("formula.", "note.", "file.")):
        return property_name
    return f"note.{property_name}"


def resolve_row_column(candidate: str, rows: list[dict[str, Any]]) -> str:
    candidate = candidate.strip()
    if not candidate:
        return ""
    candidate_lower = candidate.lower()
    for row in rows:
        for key in row:
            if key.lower() == candidate_lower:
                return key
    return ""


def language_mode_value(page_path: Path, config: dict[str, str]) -> str:
    mode = (config.get("language") or "").strip().lower()
    if not mode:
        return ""
    if mode == "all":
        return ""
    if mode == "current":
        return page_language(page_path)
    if mode == "source":
        return ""
    return mode


def page_language(path: Path) -> str:
    try:
        relative = path.resolve().relative_to(DOCS.resolve()).as_posix()
    except ValueError:
        return ""
    parts = relative.split("/")
    return parts[0] if parts else ""


def row_language(row: dict[str, Any]) -> str:
    path = row_path(row)
    if path.startswith("docs/"):
        parts = path.split("/")
        return parts[1] if len(parts) > 2 else ""
    return ""


def render_cell(value: Any, column: str, row: dict[str, Any], page_path: Path) -> str:
    if column.lower() in TECHNICAL_IDENTITY_COLUMNS:
        link = render_row_link(row, page_path, fallback=value)
        if link:
            return link
    if column.lower() == "link":
        link = render_link_value(value, page_path)
        if link:
            return link
    link = render_link_value(value, page_path)
    if link:
        return link
    return escape_table_cell(format_value(value))


def row_value(row: dict[str, Any], column: str) -> Any:
    if column in row:
        return row[column]
    lowered = column.lower()
    for key, value in row.items():
        if key.lower() == lowered:
            return value
    return None


def render_link_value(value: Any, page_path: Path) -> str:
    if isinstance(value, str):
        parsed = parse_obsidian_link(value)
        if parsed:
            target, label = parsed
            return markdown_link(label, target, page_path)
    return ""


def parse_obsidian_link(value: str) -> tuple[str, str] | None:
    stripped = value.strip()
    if not stripped.startswith("[[") or not stripped.endswith("]]"):
        return None
    body = stripped[2:-2].strip()
    if not body:
        return None
    target, _, alias = body.partition("|")
    target = target.strip()
    label = alias.strip() or PurePosixPath(target).stem
    return target, label


def render_row_link(row: dict[str, Any], page_path: Path, fallback: Any = None) -> str:
    path = row_path(row)
    if not path:
        return escape_table_cell(row_label(row, fallback))
    return markdown_link(row_label(row, fallback), path, page_path)


def row_path(row: dict[str, Any]) -> str:
    for key in ("path", "file.path", "file", "link"):
        value = row.get(key)
        path = value_path(value)
        if path:
            return path
    return ""


def value_path(value: Any) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        for key in ("path", "file", "href"):
            nested = value.get(key)
            if isinstance(nested, str):
                return nested
    return ""


def row_label(row: dict[str, Any], fallback: Any) -> str:
    for key in ("title", "name", "basename"):
        value = row.get(key)
        if isinstance(value, str) and value:
            return value
    path = row_path(row)
    if path:
        return PurePosixPath(path).stem
    return format_value(fallback)


def markdown_link(label: str, target: str, page_path: Path) -> str:
    href = markdown_href(target, page_path)
    safe_label = escape_table_cell(label.replace("[", "\\[").replace("]", "\\]"))
    return f"[{safe_label}](<{href}>)"


def markdown_href(target: str, page_path: Path) -> str:
    target = target.replace("\\", "/")
    if target.startswith("./"):
        target = target[2:]
    if target.startswith("docs/"):
        target_abs = (ROOT / target).resolve()
        try:
            current_dir = page_path.resolve().parent
            relative = posixpath.relpath(target_abs.as_posix(), current_dir.as_posix())
        except ValueError:
            relative = target
    else:
        relative = target
    href = encode_path(relative)
    if href.startswith("%"):
        return "./" + href
    return href


def encode_path(path: str) -> str:
    if "://" in path or path.startswith(("#", "/", "mailto:")):
        return path
    path_part, suffix = split_suffix(path)
    return "/".join(quote(part, safe="") for part in path_part.split("/")) + suffix


def split_suffix(path: str) -> tuple[str, str]:
    hash_index = path.find("#")
    query_index = path.find("?")
    indexes = [index for index in (hash_index, query_index) if index != -1]
    if not indexes:
        return path, ""
    index = min(indexes)
    return path[:index], path[index:]


def format_value(value: Any) -> str:
    if value is None or value == "":
        return "-"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return ", ".join(format_value(item) for item in value) or "-"
    if isinstance(value, dict):
        for key in ("display", "name", "title", "value", "path"):
            nested = value.get(key)
            if nested not in (None, ""):
                return format_value(nested)
        return ", ".join(f"{key}: {format_value(val)}" for key, val in value.items()) or "-"
    return str(value)


def table_row(values: list[str]) -> str:
    return "| " + " | ".join(escape_table_cell(value) for value in values) + " |"


def table_widths(rows: list[list[str]]) -> list[int]:
    if not rows:
        return []
    column_count = max(len(row) for row in rows)
    widths = [3 for _ in range(column_count)]
    for row in rows:
        for index, value in enumerate(row):
            widths[index] = max(widths[index], len(str(value)))
    return widths


def padded_table_row(values: list[str], widths: list[int]) -> str:
    cells = [
        str(value).ljust(widths[index] if index < len(widths) else len(str(value)))
        for index, value in enumerate(values)
    ]
    return "| " + " | ".join(cells) + " |"


def escape_table_cell(value: str) -> str:
    return str(value).replace("|", "\\|").replace("\n", "<br>")
