from __future__ import annotations

from translation.workflow import default_model, list_languages

from .discovery import PageInfo, discover_pages, read_page_info, rel
from .labels import (
    call_navigation_model,
    flattened_model_labels,
    parse_json_response,
    set_model_label,
    translate_all_nav_labels,
    translate_nav_labels,
)
from .model import (
    default_empty_model,
    load_nav_model,
    nav_model_exists,
    normalize_items,
    normalize_page,
    normalized_model,
    save_nav_model,
    slug,
    validate_items,
    validate_model,
)
from .render import (
    apply_nav_model,
    configured_languages,
    duplicate_values,
    format_nav_block,
    format_nav_entries,
    model_missing_targets,
    model_page_set,
    nav_for_language,
    nav_label,
    navigation_preview,
    replace_nav_block,
    render_model_navs,
    toml_string,
)
from .service import (
    flatten_config_nav,
    is_low_value_nav_candidate,
    items_from_config_nav,
    model_from_current_nav,
    nav_fingerprint,
    nav_scan,
    read_config_nav,
)
from .workflow_language import language_name

__all__ = [
    "PageInfo",
    "apply_nav_model",
    "call_navigation_model",
    "configured_languages",
    "default_empty_model",
    "default_model",
    "discover_pages",
    "duplicate_values",
    "flatten_config_nav",
    "flattened_model_labels",
    "format_nav_block",
    "format_nav_entries",
    "is_low_value_nav_candidate",
    "items_from_config_nav",
    "language_name",
    "list_languages",
    "load_nav_model",
    "model_from_current_nav",
    "model_missing_targets",
    "model_page_set",
    "nav_fingerprint",
    "nav_for_language",
    "nav_label",
    "nav_model_exists",
    "nav_scan",
    "navigation_preview",
    "normalize_items",
    "normalize_page",
    "normalized_model",
    "parse_json_response",
    "read_config_nav",
    "read_page_info",
    "rel",
    "render_model_navs",
    "replace_nav_block",
    "save_nav_model",
    "set_model_label",
    "slug",
    "toml_string",
    "translate_all_nav_labels",
    "translate_nav_labels",
    "validate_items",
    "validate_model",
]
